//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Domain {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NutritionalGoal {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NutritionalGoal() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.Domain.NutritionalGoal", typeof(NutritionalGoal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CalorieTarget {
            get {
                return ResourceManager.GetString("CalorieTarget", resourceCulture);
            }
        }
        
        public static string ProteinTarget {
            get {
                return ResourceManager.GetString("ProteinTarget", resourceCulture);
            }
        }
        
        public static string FatTarget {
            get {
                return ResourceManager.GetString("FatTarget", resourceCulture);
            }
        }
        
        public static string CarbsTarget {
            get {
                return ResourceManager.GetString("CarbsTarget", resourceCulture);
            }
        }
        
        public static string SaltTarget {
            get {
                return ResourceManager.GetString("SaltTarget", resourceCulture);
            }
        }
        
        public static string SugarTarget {
            get {
                return ResourceManager.GetString("SugarTarget", resourceCulture);
            }
        }
        
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        public static string NutritionalGoals {
            get {
                return ResourceManager.GetString("NutritionalGoals", resourceCulture);
            }
        }
    }
}
